print('======= DESAFIO 04 ======')
aleatorio = input('Digite qualquer coisa: ')
print('\033[35mPrimitivo: ', type(aleatorio))
print('Tem letras: ', aleatorio.isalpha())
print('Tem espaço: ', aleatorio.isspace())
print('Alphabetico e numerico =', aleatorio.isalnum())
print('É um numero =', aleatorio.isnumeric())
print('CAPS-LOCK ATIVO = ', aleatorio.isupper())
print('CAPS-LOCK DESATIVADO = ', aleatorio.islower())