m = float(input('\033[36mDistancia em metros: '))
print('A medida de {} metros corresponde a'.format(m))
print(m / 1000, 'km')
print(m / 100, 'hm')
print(m / 10, 'dam')
print(m * 10, 'dm')
print(m * 100, 'cm')
print(m * 1000, 'mm')
