nome = input('Qual é seu nome completo: ')

print('Seu nome com todas letras maiusculas')
print(nome.upper())
print('Seu nome com todas letras minusculas')
print(nome.lower())
print('Quantas letras minusculas sem considerar os espaços')
n = nome.replace(' ', '')
print(len(n))
print('Quantas letras tem o primeiro nome')
n2 = nome.split()
let = len(n2[0])
print(n2[0])
print('Seu primeiro nome tem: {} letras'.format(let))